In [1]:
import torch

In [2]:
x_ = torch.arange(8*8).reshape(1, -1)
x_.shape

torch.Size([1, 64])

In [3]:
def _split(x, parity):
        B, T = x.shape
        H, W = 8, 8
        x = x.reshape((B, H // 2, 2, W // 2, 2))

        on = x[:, :, [0, 1], :, [0, 1]]
        off = x[:, :, [0, 1], :, [1, 0]]

        on = on.permute(1, 2, 3, 0).reshape(B, T // 2)
        off = off.permute(1, 2, 3, 0).reshape(B, T // 2)

        if parity == 0:
            on, off = off, on

        return on, off

def _join(on, off, parity):
    if parity == 0:
        on, off = off, on

    B, _ = on.shape
    H, W = 8, 8

    on = on.reshape(B, H // 2, W // 2, 2)
    off = off.reshape(B, H // 2, W // 2, 2)

    x = torch.stack((on[..., 0], off[..., 0], off[..., 1], on[..., 1]), dim=3)
    x = x.reshape(B, H // 2, W // 2, 2, 2).permute(0, 1, 3, 2, 4).reshape(B, H * W)

    return x

In [7]:
_split(x_, 0)

(tensor([[ 1,  8,  3, 10,  5, 12,  7, 14, 17, 24, 19, 26, 21, 28, 23, 30, 33, 40,
          35, 42, 37, 44, 39, 46, 49, 56, 51, 58, 53, 60, 55, 62]]),
 tensor([[ 0,  9,  2, 11,  4, 13,  6, 15, 16, 25, 18, 27, 20, 29, 22, 31, 32, 41,
          34, 43, 36, 45, 38, 47, 48, 57, 50, 59, 52, 61, 54, 63]]))

In [6]:
_join(*_split(x_, 0), 0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])